name: Deploy React App
on: 
  push:
    branches:
      - master
    # paths-ignore:
    #   - '.github/workflows'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repozitory code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/checkout@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-losk.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get repozitory code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/checkout@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-losk.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get repozitory code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/checkout@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-losk.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying ...
